# Generated by Django 4.1.5 on 2023-05-14 22:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0004_produit_studentprofil_staffprofil"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="image",
        ),
    ]
