# Generated by Django 4.1.5 on 2023-05-14 23:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Main", "0005_remove_produit_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="quantite",
        ),
    ]
